// Textos de la comunidad en español e inglés, separados de la página.

export const communityContent = {
    es: {
        volver: '← Volver al inicio',
        pageTitle: 'Comunidad',
        pageSubtitle: 'Comparte tus propias creaciones LEGO y descubre las de otros fans.',
        steps: ['Crea tu cuenta gratis', 'Publica tu foto', 'Recibe me gusta'],
        connectedAs: 'Conectado como',
        logout: 'Cerrar sesión',
        newPostTitle: 'Nueva publicación',
        placeholder: '¿Qué diorama o creación quieres compartir hoy?',
        instagramUrlPlaceholder: 'URL de tu perfil de Instagram (ej. https://instagram.com/tu_usuario)',
        categoryLabel: 'Categoría (opcional)',
        publishBtn: 'Publicar',
        publishingBtn: 'Publicando…',
        filterAll: 'Todo',
        filterMine: 'Mis publicaciones',
        sortRecent: 'Recientes',
        sortPopular: 'Más gustados',
        noPosts: 'Aún no hay publicaciones en el foro.',
        noResultsFilter: 'No hay publicaciones que coincidan con este filtro.',
        edit: 'Editar',
        delete: 'Borrar',
        save: 'Guardar',
        cancel: 'Cancelar',
        close: 'Cerrar',
        confirmDeleteTitle: '¿Eliminar esta publicación?',
        confirmDeleteDesc: 'Esta acción no se puede deshacer.',
        mustLoginLike: 'Debes iniciar sesión para dar "Me gusta".',
        mustLogin: 'Debes iniciar sesión.',
        fillForm: 'Completa el mensaje y selecciona una imagen.',
        badFormat: 'Formato no permitido. Usa JPG, PNG, WEBP o GIF.',
        badUrl: 'El enlace debe empezar por http:// o https://.',
        fileLabel: 'Foto a publicar',
        likeError: 'No se pudo registrar tu me gusta. Inténtalo de nuevo.',
        deleteForbidden: 'No se pudo eliminar la publicación.',
        tooLarge: (mb: number) => `La imagen supera los ${mb}MB permitidos.`,
        anonymous: 'Anónimo',
        viewProfile: 'Ver perfil',
        activity: 'Actividad',
        profile: 'Mi perfil',
        auth: {
            joinTitle: 'Únete a la comunidad',
            joinDesc: 'Crea una cuenta gratis o inicia sesión para publicar tus fotos y dar me gusta.',
            signUpBtn: 'Registrarte',
            loginBtn: 'Iniciar sesión',
        }
    },
    en: {
        volver: '← Back to home',
        pageTitle: 'Community',
        pageSubtitle: 'Share your own LEGO creations and discover other fans’.',
        steps: ['Create a free account', 'Post your photo', 'Get likes'],
        connectedAs: 'Logged in as',
        logout: 'Log out',
        newPostTitle: 'New post',
        placeholder: 'What diorama or creation do you want to share today?',
        instagramUrlPlaceholder: 'Your Instagram profile URL (e.g. https://instagram.com/your_account)',
        categoryLabel: 'Category (optional)',
        publishBtn: 'Post',
        publishingBtn: 'Posting…',
        filterAll: 'All',
        filterMine: 'My posts',
        sortRecent: 'Recent',
        sortPopular: 'Most liked',
        noPosts: 'No posts in the forum yet.',
        noResultsFilter: 'No posts match this filter.',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        confirmDeleteTitle: 'Delete this post?',
        confirmDeleteDesc: 'This action cannot be undone.',
        mustLoginLike: 'You must log in to like posts.',
        mustLogin: 'You must log in.',
        fillForm: 'Complete the message and select an image.',
        badFormat: 'Unsupported format. Use JPG, PNG, WEBP or GIF.',
        badUrl: 'The link must start with http:// or https://.',
        fileLabel: 'Photo to post',
        likeError: 'Your like could not be saved. Please try again.',
        deleteForbidden: 'The post could not be deleted.',
        tooLarge: (mb: number) => `The image exceeds the ${mb}MB limit.`,
        anonymous: 'Anonymous',
        viewProfile: 'View profile',
        activity: 'Activity',
        profile: 'My profile',
        auth: {
            joinTitle: 'Join the community',
            joinDesc: 'Create a free account or log in to post your photos and give likes.',
            signUpBtn: 'Sign up',
            loginBtn: 'Log in',
        }
    }
};

export type CommunityContent = (typeof communityContent)['es'];
